---
- name: Deploy Amazon WAR to Tomcat
  hosts: all
  become: yes
  vars_files:
    - ../vault/credentials.yml   # Encrypted secrets

  tasks:
    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ playbook_dir }}/../../target/Amazon.war"
        dest: /opt/tomcat/webapps/Amazon.war
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat service
      systemd:
        name: tomcat
        state: restarted

