---
- hosts: tomcat_servers
  become: yes
  vars_files:
    - ../vault/credentials.yml
  tasks:
    - name: Copy WAR file to Tomcat server
      copy:
        src: /var/lib/jenkins/workspace/Amazon-Jenkins_sonar-CI/target/Amazon.war
        dest: /opt/tomcat9/webapps/Amazon.war
        mode: '0644'

    - name: Restart Tomcat service
      systemd:
        name: tomcat9
        state: restarted

