---
- name: Deploy Amazon WAR to Tomcat
  hosts: all
  become: yes
  vars_files:
    - ../vault/credentials.yml   # Encrypted secrets

  tasks:
    - name: Copy WAR file to Tomcat webapps
      copy:
        src: /var/lib/jenkins/workspace/Amazon-Jenkins_sonar-CI/target/Amazon.war 
        dest: /home/hamdu/tomcat/webapps/Amazon.war
        owner: hamdu 
        group: hamdu 
        mode: '0644'

    - name: Restart Tomcat service
      systemd:
        name: tomcat
        state: restarted

