---
- hosts: tomcat_servers
  become: yes
  vars_files:
    - ../vault/credentials.yml
  tasks:
    - name: Copy WAR file to Tomcat server
      copy:
        src: /var/lib/jenkins/workspace/Amazon-Jenkins_sonar-CI/target/             
        dest: /home/hamdu/tomcat/webapps/Amazon.war

    - name: Restart Tomcat service
      systemd:
        name: tomcat
        state: restarted

