---
- hosts: test_servers
  become: yes
  vars_files:
    - ../vault/credentials.yml

  vars:
    tomcat_version: 9.0.108
    tomcat_install_dir: /home/hamdu/tomcat
    war_src: /var/lib/jenkins/workspace/Amazon-Jenkins_sonar-CI/target/Amazon.war
    war_dest: "{{ tomcat_install_dir }}/webapps/Amazon.war"

  tasks:
    - name: Ensure Java is installed
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Tomcat install directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: hamdu
        group: hamdu
        mode: '0755'

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Deploy tomcat-users.xml from template
      template:
        src: tomcat-users.xml.j2
        dest: "{{ tomcat_install_dir }}/conf/tomcat-users.xml"
        owner: hamdu
        group: hamdu
        mode: '0644'

    - name: Make Tomcat startup scripts executable
      file:
        path: "{{ tomcat_install_dir }}/bin/{{ item }}"
        mode: '0755'
      loop:
        - startup.sh
        - catalina.sh
        - shutdown.sh

    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ war_src }}"
        dest: "{{ war_dest }}"
        owner: hamdu
        group: hamdu
        mode: '0644'

    - name: Deploy WAR via Tomcat Manager API
      uri:
        url: "http://localhost:8080/manager/text/deploy?path=/Amazon&update=true"
        method: PUT
        user: "{{ tomcat_admin_user }}"
        password: "{{ tomcat_admin_password }}"
        force_basic_auth: yes
        status_code: [200, 201, 204]
        body: "{{ lookup('file', war_dest) }}"
        headers:
          Content-Type: application/octet-stream

    - name: Start Tomcat
      shell: "{{ tomcat_install_dir }}/bin/startup.sh"
      args:
        chdir: "{{ tomcat_install_dir }}/bin"
      become: yes
      become_user: hamdu

